// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

void Cambia_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Fondo1;
extern lv_obj_t * ui_Menu1;
extern lv_obj_t * ui_Fondo2;
extern lv_obj_t * ui_Menu2;
extern lv_obj_t * ui_Fondo3;
extern lv_obj_t * ui_Menu3;
extern lv_obj_t * ui_Fondo4;
extern lv_obj_t * ui_Menu4;
extern lv_obj_t * ui_msgbox;
extern lv_obj_t * ui_msgtxt1;
extern lv_obj_t * ui_msgtxt2;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui____initial_actions0;





LV_FONT_DECLARE(ui_font_OpenSans102);
LV_FONT_DECLARE(ui_font_OpenSans24);
LV_FONT_DECLARE(ui_font_OpenSans52);
LV_FONT_DECLARE(ui_font_OpenSansCSB42);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
